baseURL = 'https://wtfis.top/'
languageCode = 'en-us'
title = 'WTF is'
theme = "hugo-seo-theme"

[params]
description = "WTF is a collection of tech terms explained in simple words."
netlify_deployment_status_badge = "https://api.netlify.com/api/v1/badges/9c167a9f-5acf-4cd6-87b8-6704c912759e/deploy-status"